apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 4 
  selector:
    matchLabels:
      app: myapp
      replicas: blue 
  template:
    metadata:
      labels:
        app: myapp
        replicas: blue 
    spec:
      containers:
      - name: myapp-cont
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactjs-app
spec:
  replicas: 4 
  selector:
    matchLabels:
      app: myapp
      replicas: green
  template:
    metadata:
      labels:
        app: myapp
        replicas: green
    spec:
      containers:
      - name: myapp-cont
        image: 69966/earthdx:78
        ports:
        - containerPort: 80
