nfs_server: 
  ip:  "{{ hostvars['master01']['private_ip'] }}"
  mount_path: /srv/nfs_shared
nfs_client:
  mount_path: /mnt/nfs_shared
  
  ips: 
    - "{{ hostvars['master02']['private_ip'] }}"
    - "{{ hostvars['master03']['private_ip'] }}"
    - "{{ hostvars['worker01']['private_ip'] }}"
    - "{{ hostvars['worker02']['private_ip'] }}"