[all:vars]
ansible_user=kk
ansible_python_interpreter=/usr/bin/python3
; for first ssh, no need to answer yes no 
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[nfs-servers]
master01 ansible_host=136.85.120.66 private_ip=10.148.0.2 ansible_connection=local 

[nfs-clients]
master02 private_ip=10.148.0.10 ansible_host=35.247.155.233 
master03 private_ip=10.148.0.11 ansible_host=34.158.53.15
worker01 private_ip=10.184.0.6 ansible_host=34.101.111.120
worker02 private_ip=10.184.0.7 ansible_host=34.101.233.40


[all:children]
nfs-servers
nfs-clients


; ansible -i inventory.ini -m ping node1 
; ansible -i inventory.ini -m ping all 
; ansible -i inventory.ini -m command -a "uptime" all 
; ansible -i inventory.ini -m apt -a "name=nginx state=present" node2 -b