apiVersion: v1
kind: Pod
metadata:
  name: demo-nginx-app
  labels:
    app.kubernetes.io/name: demo-nginx-app
spec:
  containers:
  - name: demo-nginx-app
    image: nginx:alpine
    ports:
      - containerPort: 80


# kubectl apply -f demo-pod.yaml 
# kubectl apply -f . 
