apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dpl
spec:
  # strategy that we specific here as well. 
  
  replicas: 10
  selector:
    matchLabels:
      app: nginx-dpl
  template:
    metadata:
      labels:
        app: nginx-dpl
    spec:
      containers:
      - name: nginx-dpl
        image: nginx:alpine
        ports:
        - containerPort: 80
