- name: Install Nfs client
  when: true   
  apt: 
    name: nfs-common 
    state: present 
- name: Create the directory for mounting 
  file: 
    path: "{{ nfs_client.mount_path}}"
    state: directory 
    owner: "nobody"
    group: "nogroup"
    mode: "0777"
# mount 192.168.56.10:/srv/nfs_shared /mnt/nfs_shared
- name: Mount the client path to server path 
  mount: 
    src: "{{nfs_server.ip}}:{{nfs_server.mount_path}}"
    path: "{{nfs_client.mount_path}}"
    fstype: nfs 
    opts: defaults,_netdev
    state: mounted
# /etc/fstab
- name: Persist the mount ( after restart still recognize the server )
  mount: 
    src: "{{nfs_server.ip}}:{{nfs_server.mount_path}}"
    path: "{{nfs_client.mount_path}}"
    fstype: nfs 
    opts: defaults,_netdev
    state: present
