[all:vars]
ansible_user=kk
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'


[localhost]
node1 ansible_connection=local

[masters]
master02 ansible_host=35.247.155.233
master03 ansible_host=34.158.53.15


[workers]
worker01 ansible_host=34.101.111.120
worker02 ansible_host=34.101.233.40
