#!/bin/bash


ping-all: 
    ansible -m ping all 
ping-masters: 
    ansible -m ping masters
ping-workers: 
    ansible -m ping workers 
create-masters: 
    ansible-playbook playbook/create-masters.yaml
create-workers: 
    ansible-playbook playbook/create-workers.yaml
destroy: 
    ansible-playbook playbook/destroy-all.yaml 