apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dpl
spec:
  strategy: 
    rollingUpdate:
      maxSurge: 1 # 25% extra pod that will create during update
      maxUnavailable: 1 #25%  pod that can be unavailable during update
  replicas: 10
  selector:
    matchLabels:
      app: nginx-dpl
  template:
    metadata:
      labels:
        app: nginx-dpl
    spec:
      containers:
      - name: nginx-dpl
        image: nginx:latest
        ports:
        - containerPort: 80
