- name: Deploy Spring File Upload Service 
  hosts: node2
  vars: 
    workdirectory: "/home/kk"
  tasks: 
    
  # ensure that the server has already installed docker and docker compose
    # should create a customer directory for this service 
    # we have multiple directory for multiple 
    - name: Copy docker compose configuration to node2 
      copy: 
        src: ../config/docker-compose.yaml
        dest: "{{workdirectory}}/docker-compose.yaml"
    - name: Run the compose file 
      command: docker compose up -d 
      args:
        chdir: "{{workdirectory}}"
        