server {
    listen 80;
    listen [::]:80;

    server_name nexus.example.com;

    # Allow uploads up to 10 GB

    location / {
        proxy_pass http://localhost:8081/;

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Recommended for large uploads
        proxy_request_buffering off;
        proxy_buffering off;
        proxy_read_timeout 900;
        proxy_send_timeout 900;
    }
}